### PR TITLE
Scrape the new 6th Legislative Council pages instead

### PR DESCRIPTION
**Pull request by mhl**
There has recently been an election in Hong Kong. We have archived the
data from the 5th Legislative Council, but now need to update the scraper
to fetch members from the new 6th Legislative Council instead.

(Note for the pull request, not in the commit mesage: the plan is to deploy
this under the everypolitician-scrapers account on morph.io.)

### CODE REVIEW

**Review by tmtmtmtm — COMMENTED** [review]
We've discovered that it's generally only sensible to have the scraper generate the terms table if the data in it is actually being _scraped_ from that source. Otherwise, it's a lot better to just have the terms table in `everypolitician-data` maintained there. Switching this to a manually maintained file would avoid most of the work here, and be a lot easier to change in future.

**Comment by tmtmtmtm** [comment]
Also, if the database needs to be deleted before run, this is a good opportunity to move the scraper on morph from Struan's account into the everypolitician-scrapers one (the only value in keeping it in an existing personal account is if there's history that would go missing on a fresh run). Then anyone in the team will be able to stop / start it, set the necessary morph vars, etc.

**Comment by mhl** [comment]
OK, I've archived the terms table with just term 5 in this pull request: https://github.com/everypolitician/everypolitician-data/pull/19158

**Comment by mhl** [comment]
@tmtmtmtm I've revised this - it's a much simpler change now.

**Review by tmtmtmtm — APPROVED** [review]
LGTM!

**Pull request merged**
